[package]
name = "tcping"
version = "1.0.0"
authors = ["Dely <noreply>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1"
chrono = "0.4"
dns-lookup = "2.0"
